"""Shared project and data paths used by builders and visualizers."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DATA_ROOT = PROJECT_ROOT / "raw_data"

N02_RELEASE = "24"
N02_DATASET_ID = f"N02-{N02_RELEASE}"
N02_GML_ROOT = RAW_DATA_ROOT / f"{N02_DATASET_ID}_GML"
N02_UTF8_ROOT = N02_GML_ROOT / "UTF-8"
N02_XML_PATH = N02_UTF8_ROOT / f"{N02_DATASET_ID}.xml"
N02_ZIP_PATH = RAW_DATA_ROOT / f"{N02_DATASET_ID}_GML.zip"

S12_RELEASE = "25"
S12_DATA_YEAR = 2024
S12_DATASET_ID = f"S12-{S12_RELEASE}"
S12_GML_ROOT = RAW_DATA_ROOT / f"{S12_DATASET_ID}_GML"
S12_UTF8_ROOT = S12_GML_ROOT / "UTF-8"
S12_XML_PATH = S12_UTF8_ROOT / f"{S12_DATASET_ID}.xml"
S12_ZIP_PATH = RAW_DATA_ROOT / f"{S12_DATASET_ID}_GML.zip"
